{{- if .Values.use_gateway_api }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: vault-gateway
  namespace: {{ .Values.namespace }}
  annotations:
    networking.gke.io/certmap: {{ .Values.certificate_map_name }}

spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
  addresses:
  - type: NamedAddress
    value: {{ .Values.lb_ip_address_name }}
{{- end }}
