apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: vault-health-policy
  namespace: {{ .Values.namespace }}
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 3
    unhealthyThreshold: 2
    config:
      type: HTTPS
      httpsHealthCheck:
        port: 8200
        portSpecification: USE_FIXED_PORT
        requestPath: /v1/sys/health?perfstandbyok=false
  targetRef:
    group: ""
    kind: Service
    name: vault-external