apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ .Values.podmonitor_name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  endpoints:
  - port: 8200
    interval: 30s
    path: /v1/sys/metrics
    params:
      format:
        - prometheus
    scheme: https
    tls:
      insecureSkipVerify: true
